rest-template:
  connectTimeout: 300000
  readTimeout: 300000
  getBookUrl: http://localhost:8081/api/book/
  tokenUrl: http://localhost:8081/token
  login: user
  password: pass

spring:
  kafka:
    bootstrap-servers: localhost:9092

library:
  kafka-topic-add-book-name: add-book