rest-template:
  connectTimeout: 300000
  readTimeout: 300000
  getBookUrl: http://localhost:8081/api/book/
  tokenUrl: http://localhost:8081/token
  login: user
  password: pass

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true

spring:
  kafka:
    bootstrap-servers: localhost:9092

library:
  kafka-topic-add-book-name: add-book

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 2
        minimumNumberOfCalls: 1
        permittedNumberOfCallsInHalfOpenState: 1
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 50s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        slowCallDurationThreshold: 1s
#        recordExceptions:
#          - org.springframework.web.client.HttpServerErrorException
#          - java.util.concurrent.TimeoutException
#          - java.io.IOException
    instances:
      mainService:
        baseConfig: default