server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true

logging:
  level:
    root: info
  file:
    name: "log.txt"

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    initialization-mode: always
    data: classpath:data.sql
  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate

    show-sql: true

jwt:
  privateKey: classpath:app.key
  publicKey: classpath:app.pub