DROP TABLE IF EXISTS BOOK_COMMENTS;
DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS GENRES;

CREATE TABLE AUTHORS(ID BIGINT AUTO_INCREMENT PRIMARY KEY, FIO VARCHAR(255));

CREATE TABLE GENRES(ID BIGINT AUTO_INCREMENT PRIMARY KEY, NAME VARCHAR(255));

CREATE TABLE BOOKS(ID BIGINT AUTO_INCREMENT PRIMARY KEY, TITLE VARCHAR(255), AUTHOR_ID BIGINT, GENRE_ID BIGINT);

CREATE TABLE BOOK_COMMENTS(ID BIGINT AUTO_INCREMENT PRIMARY KEY, BOOK_ID BIGINT, COMMENT VARCHAR(255));

ALTER TABLE BOOKS ADD FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(ID);
ALTER TABLE BOOKS ADD FOREIGN KEY (GENRE_ID) REFERENCES GENRES(ID);
ALTER TABLE BOOK_COMMENTS ADD FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(ID);